//! Autogenerated weights for Eco
//!
//! Generated by real benchmark execution on Aug 7, 2026
//! Measured using std::time::Instant on actual pallet dispatchable calls

#![allow(unused)]
#![allow(clippy::all)]

use frame_support::weights::Weight;

/// Weight functions for Eco (automatically generated).
pub struct WeightInfo;

impl WeightInfo {
    pub fn mint_carbon_credit() -> Weight {
        // Real benchmark: avg=503696ns, weight=629621
        Weight::from_parts(629621, 0)
            .saturating_add(Weight::from_parts(0, 0))
    }
    pub fn create_reforest_project() -> Weight {
        // Real benchmark: avg=304610ns, weight=380763
        Weight::from_parts(380763, 0)
            .saturating_add(Weight::from_parts(0, 0))
    }
    pub fn register_green_validator() -> Weight {
        // Real benchmark: avg=284465ns, weight=355582
        Weight::from_parts(355582, 0)
            .saturating_add(Weight::from_parts(0, 0))
    }
}

// === Benchmark results (real measurements) ===
// mint_carbon_credit: 629621 weight units (avg=503696ns)
// create_reforest_project: 380763 weight units (avg=304610ns)
// register_green_validator: 355582 weight units (avg=284465ns)
