
//! Autogenerated weights for `pallet_eco`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 58.0.0
//! DATE: 2026-08-09, STEPS: `20`, REPEAT: `10`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `ubuntu-32gb-nbg1-2`, CPU: `AMD EPYC-Milan Processor`
//! WASM-EXECUTION: `Compiled`, CHAIN: `Some("dev")`, DB CACHE: 1024

// Executed Command:
// ./target/release/verdis
// benchmark
// pallet
// --chain
// dev
// --pallet
// pallet_eco
// --extrinsic
// *
// --steps
// 20
// --repeat
// 10
// --output
// /tmp/weights_eco.rs
// --template
// node/src/weight-template.hbs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::Weight};
use core::marker::PhantomData;

/// Weight functions for `pallet_eco`.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> crate::WeightInfo for SubstrateWeight<T> {
	/// Storage: `Eco::CarbonCredits` (r:3 w:1)
	/// Proof: `Eco::CarbonCredits` (`max_values`: None, `max_size`: Some(328), added: 2803, mode: `MaxEncodedLen`)
	/// Storage: `Eco::TotalCO2Offset` (r:1 w:1)
	/// Proof: `Eco::TotalCO2Offset` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	fn mint_carbon_credit() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `494`
		//  Estimated: `9399`
		// Minimum execution time: 22_904_000 picoseconds.
		Weight::from_parts(25_408_000, 0)
			.saturating_add(Weight::from_parts(0, 9399))
			.saturating_add(T::DbWeight::get().reads(4))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	/// Storage: `Eco::CarbonCredits` (r:1 w:1)
	/// Proof: `Eco::CarbonCredits` (`max_values`: None, `max_size`: Some(328), added: 2803, mode: `MaxEncodedLen`)
	fn verify_carbon_credit() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `302`
		//  Estimated: `3793`
		// Minimum execution time: 13_300_000 picoseconds.
		Weight::from_parts(14_632_000, 0)
			.saturating_add(Weight::from_parts(0, 3793))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `Eco::CarbonCredits` (r:1 w:1)
	/// Proof: `Eco::CarbonCredits` (`max_values`: None, `max_size`: Some(328), added: 2803, mode: `MaxEncodedLen`)
	/// Storage: `Eco::TotalCreditsRetired` (r:1 w:1)
	/// Proof: `Eco::TotalCreditsRetired` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	fn retire_carbon_credit() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `302`
		//  Estimated: `3793`
		// Minimum execution time: 16_355_000 picoseconds.
		Weight::from_parts(17_847_000, 0)
			.saturating_add(Weight::from_parts(0, 3793))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	/// Storage: `Eco::CarbonCredits` (r:1 w:1)
	/// Proof: `Eco::CarbonCredits` (`max_values`: None, `max_size`: Some(328), added: 2803, mode: `MaxEncodedLen`)
	fn transfer_carbon_credit() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `302`
		//  Estimated: `3793`
		// Minimum execution time: 13_380_000 picoseconds.
		Weight::from_parts(14_602_000, 0)
			.saturating_add(Weight::from_parts(0, 3793))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `Eco::ReforestProjects` (r:3 w:1)
	/// Proof: `Eco::ReforestProjects` (`max_values`: None, `max_size`: Some(350), added: 2825, mode: `MaxEncodedLen`)
	/// Storage: `Eco::TotalTreesPlanted` (r:1 w:1)
	/// Proof: `Eco::TotalTreesPlanted` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	fn create_reforest_project() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `264`
		//  Estimated: `9465`
		// Minimum execution time: 21_803_000 picoseconds.
		Weight::from_parts(23_816_000, 0)
			.saturating_add(Weight::from_parts(0, 9465))
			.saturating_add(T::DbWeight::get().reads(4))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	/// Storage: `Eco::ReforestProjects` (r:1 w:1)
	/// Proof: `Eco::ReforestProjects` (`max_values`: None, `max_size`: Some(350), added: 2825, mode: `MaxEncodedLen`)
	fn update_reforest_project() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `258`
		//  Estimated: `3815`
		// Minimum execution time: 13_249_000 picoseconds.
		Weight::from_parts(14_692_000, 0)
			.saturating_add(Weight::from_parts(0, 3815))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `Eco::ReforestProjects` (r:1 w:1)
	/// Proof: `Eco::ReforestProjects` (`max_values`: None, `max_size`: Some(350), added: 2825, mode: `MaxEncodedLen`)
	fn verify_reforest_project() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `258`
		//  Estimated: `3815`
		// Minimum execution time: 13_320_000 picoseconds.
		Weight::from_parts(14_601_000, 0)
			.saturating_add(Weight::from_parts(0, 3815))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `Eco::GreenValidators` (r:8 w:1)
	/// Proof: `Eco::GreenValidators` (`max_values`: None, `max_size`: Some(168), added: 2643, mode: `MaxEncodedLen`)
	fn register_green_validator() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `880`
		//  Estimated: `22134`
		// Minimum execution time: 40_541_000 picoseconds.
		Weight::from_parts(43_886_000, 0)
			.saturating_add(Weight::from_parts(0, 22134))
			.saturating_add(T::DbWeight::get().reads(8))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `Eco::GreenValidators` (r:1 w:1)
	/// Proof: `Eco::GreenValidators` (`max_values`: None, `max_size`: Some(168), added: 2643, mode: `MaxEncodedLen`)
	fn update_green_score() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `485`
		//  Estimated: `3633`
		// Minimum execution time: 16_114_000 picoseconds.
		Weight::from_parts(17_917_000, 0)
			.saturating_add(Weight::from_parts(0, 3633))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
}
