
//! Autogenerated weights for `pallet_eco`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 58.0.0
//! DATE: 2026-08-13, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `ubuntu-32gb-nbg1-2`, CPU: `AMD EPYC-Milan Processor`
//! WASM-EXECUTION: `Compiled`, CHAIN: `Some("dev")`, DB CACHE: 1024

// Executed Command:
// ./target/release/verdis
// benchmark
// pallet
// --chain=dev
// --pallet=pallet_eco
// --extrinsic=*
// --output=pallets/eco/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::Weight};
use core::marker::PhantomData;

/// Weight functions for `pallet_eco`.
pub struct WeightInfo<T>(PhantomData<T>);
impl<T: frame_system::Config> crate::WeightInfo for WeightInfo<T> {
	/// Storage: `Eco::CarbonCredits` (r:3 w:1)
	/// Proof: `Eco::CarbonCredits` (`max_values`: None, `max_size`: Some(328), added: 2803, mode: `MaxEncodedLen`)
	/// Storage: `Eco::LastMintBlock` (r:1 w:1)
	/// Proof: `Eco::LastMintBlock` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Eco::CreditsMintedThisBlock` (r:1 w:1)
	/// Proof: `Eco::CreditsMintedThisBlock` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Eco::TotalCO2Offset` (r:1 w:1)
	/// Proof: `Eco::TotalCO2Offset` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	fn mint_carbon_credit() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `528`
		//  Estimated: `9399`
		// Minimum execution time: 25_248_000 picoseconds.
		Weight::from_parts(29_345_000, 0)
			.saturating_add(Weight::from_parts(0, 9399))
			.saturating_add(T::DbWeight::get().reads(6))
			.saturating_add(T::DbWeight::get().writes(4))
	}
	/// Storage: `Eco::CarbonCredits` (r:1 w:1)
	/// Proof: `Eco::CarbonCredits` (`max_values`: None, `max_size`: Some(328), added: 2803, mode: `MaxEncodedLen`)
	fn verify_carbon_credit() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `359`
		//  Estimated: `3793`
		// Minimum execution time: 13_591_000 picoseconds.
		Weight::from_parts(15_914_000, 0)
			.saturating_add(Weight::from_parts(0, 3793))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `Eco::CarbonCredits` (r:1 w:1)
	/// Proof: `Eco::CarbonCredits` (`max_values`: None, `max_size`: Some(328), added: 2803, mode: `MaxEncodedLen`)
	/// Storage: `Eco::TotalCreditsRetired` (r:1 w:1)
	/// Proof: `Eco::TotalCreditsRetired` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	fn retire_carbon_credit() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `359`
		//  Estimated: `3793`
		// Minimum execution time: 16_585_000 picoseconds.
		Weight::from_parts(19_148_000, 0)
			.saturating_add(Weight::from_parts(0, 3793))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	/// Storage: `Eco::CarbonCredits` (r:1 w:1)
	/// Proof: `Eco::CarbonCredits` (`max_values`: None, `max_size`: Some(328), added: 2803, mode: `MaxEncodedLen`)
	fn transfer_carbon_credit() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `359`
		//  Estimated: `3793`
		// Minimum execution time: 13_841_000 picoseconds.
		Weight::from_parts(16_265_000, 0)
			.saturating_add(Weight::from_parts(0, 3793))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `Eco::ReforestProjects` (r:3 w:1)
	/// Proof: `Eco::ReforestProjects` (`max_values`: None, `max_size`: Some(350), added: 2825, mode: `MaxEncodedLen`)
	/// Storage: `Eco::TotalTreesPlanted` (r:1 w:1)
	/// Proof: `Eco::TotalTreesPlanted` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	fn create_reforest_project() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `298`
		//  Estimated: `9465`
		// Minimum execution time: 21_843_000 picoseconds.
		Weight::from_parts(26_109_000, 0)
			.saturating_add(Weight::from_parts(0, 9465))
			.saturating_add(T::DbWeight::get().reads(4))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	/// Storage: `Eco::ReforestProjects` (r:1 w:1)
	/// Proof: `Eco::ReforestProjects` (`max_values`: None, `max_size`: Some(350), added: 2825, mode: `MaxEncodedLen`)
	fn update_reforest_project() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `292`
		//  Estimated: `3815`
		// Minimum execution time: 13_240_000 picoseconds.
		Weight::from_parts(15_564_000, 0)
			.saturating_add(Weight::from_parts(0, 3815))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `Eco::ReforestProjects` (r:1 w:1)
	/// Proof: `Eco::ReforestProjects` (`max_values`: None, `max_size`: Some(350), added: 2825, mode: `MaxEncodedLen`)
	fn verify_reforest_project() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `292`
		//  Estimated: `3815`
		// Minimum execution time: 13_290_000 picoseconds.
		Weight::from_parts(15_463_000, 0)
			.saturating_add(Weight::from_parts(0, 3815))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `Eco::GreenValidators` (r:8 w:1)
	/// Proof: `Eco::GreenValidators` (`max_values`: None, `max_size`: Some(168), added: 2643, mode: `MaxEncodedLen`)
	fn register_green_validator() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `914`
		//  Estimated: `22134`
		// Minimum execution time: 40_440_000 picoseconds.
		Weight::from_parts(46_281_000, 0)
			.saturating_add(Weight::from_parts(0, 22134))
			.saturating_add(T::DbWeight::get().reads(8))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `Eco::GreenValidators` (r:1 w:1)
	/// Proof: `Eco::GreenValidators` (`max_values`: None, `max_size`: Some(168), added: 2643, mode: `MaxEncodedLen`)
	fn update_green_score() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `519`
		//  Estimated: `3633`
		// Minimum execution time: 16_655_000 picoseconds.
		Weight::from_parts(19_070_000, 0)
			.saturating_add(Weight::from_parts(0, 3633))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
}
