
//! Autogenerated weights for `pallet_amm_dex`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 58.0.0
//! DATE: 2026-08-09, STEPS: `20`, REPEAT: `10`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `ubuntu-32gb-nbg1-2`, CPU: `AMD EPYC-Milan Processor`
//! WASM-EXECUTION: `Compiled`, CHAIN: `Some("dev")`, DB CACHE: 1024

// Executed Command:
// ./target/release/verdis
// benchmark
// pallet
// --chain
// dev
// --pallet
// pallet_amm_dex
// --extrinsic
// *
// --steps
// 20
// --repeat
// 10
// --output
// /tmp/weights_amm_dex.rs
// --template
// node/src/weight-template.hbs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::Weight};
use core::marker::PhantomData;

/// Weight functions for `pallet_amm_dex`.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> crate::WeightInfo for SubstrateWeight<T> {
	/// Storage: `AmmDex::PoolCount` (r:1 w:1)
	/// Proof: `AmmDex::PoolCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `AmmDex::PoolByPair` (r:1 w:1)
	/// Proof: `AmmDex::PoolByPair` (`max_values`: None, `max_size`: Some(86), added: 2561, mode: `MaxEncodedLen`)
	/// Storage: `AmmDex::Pools` (r:0 w:1)
	/// Proof: `AmmDex::Pools` (`max_values`: None, `max_size`: Some(178), added: 2653, mode: `MaxEncodedLen`)
	/// Storage: `AmmDex::LiquidityProviders` (r:0 w:1)
	/// Proof: `AmmDex::LiquidityProviders` (`max_values`: None, `max_size`: Some(84), added: 2559, mode: `MaxEncodedLen`)
	fn create_pool() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `166`
		//  Estimated: `3551`
		// Minimum execution time: 46_631_000 picoseconds.
		Weight::from_parts(49_725_000, 0)
			.saturating_add(Weight::from_parts(0, 3551))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(4))
	}
	/// Storage: `AmmDex::Pools` (r:1 w:1)
	/// Proof: `AmmDex::Pools` (`max_values`: None, `max_size`: Some(178), added: 2653, mode: `MaxEncodedLen`)
	/// Storage: `AmmDex::LiquidityProviders` (r:1 w:1)
	/// Proof: `AmmDex::LiquidityProviders` (`max_values`: None, `max_size`: Some(84), added: 2559, mode: `MaxEncodedLen`)
	/// The range of component `n` is `[1, 10]`.
	fn add_liquidity(_n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `431`
		//  Estimated: `3643`
		// Minimum execution time: 47_181_000 picoseconds.
		Weight::from_parts(50_406_262, 0)
			.saturating_add(Weight::from_parts(0, 3643))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	/// Storage: `AmmDex::Pools` (r:1 w:1)
	/// Proof: `AmmDex::Pools` (`max_values`: None, `max_size`: Some(178), added: 2653, mode: `MaxEncodedLen`)
	/// Storage: `AmmDex::LiquidityProviders` (r:1 w:1)
	/// Proof: `AmmDex::LiquidityProviders` (`max_values`: None, `max_size`: Some(84), added: 2559, mode: `MaxEncodedLen`)
	fn remove_liquidity() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `431`
		//  Estimated: `3643`
		// Minimum execution time: 49_294_000 picoseconds.
		Weight::from_parts(52_589_000, 0)
			.saturating_add(Weight::from_parts(0, 3643))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	/// Storage: `AmmDex::Pools` (r:1 w:1)
	/// Proof: `AmmDex::Pools` (`max_values`: None, `max_size`: Some(178), added: 2653, mode: `MaxEncodedLen`)
	/// Storage: `AmmDex::TotalVolume` (r:1 w:1)
	/// Proof: `AmmDex::TotalVolume` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `AmmDex::TotalSwaps` (r:1 w:1)
	/// Proof: `AmmDex::TotalSwaps` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	fn swap() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `359`
		//  Estimated: `3643`
		// Minimum execution time: 44_617_000 picoseconds.
		Weight::from_parts(47_873_000, 0)
			.saturating_add(Weight::from_parts(0, 3643))
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	/// Storage: `AmmDex::TokenPoolCount` (r:1 w:1)
	/// Proof: `AmmDex::TokenPoolCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `AmmDex::TokenPoolByPair` (r:1 w:1)
	/// Proof: `AmmDex::TokenPoolByPair` (`max_values`: None, `max_size`: Some(38), added: 2513, mode: `MaxEncodedLen`)
	/// Storage: `FungibleTokens::TokenBalances` (r:2 w:2)
	/// Proof: `FungibleTokens::TokenBalances` (`max_values`: None, `max_size`: Some(88), added: 2563, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `FungibleTokens::Tokens` (r:1 w:0)
	/// Proof: `FungibleTokens::Tokens` (`max_values`: None, `max_size`: Some(124), added: 2599, mode: `MaxEncodedLen`)
	/// Storage: `AmmDex::TokenPools` (r:0 w:1)
	/// Proof: `AmmDex::TokenPools` (`max_values`: None, `max_size`: Some(130), added: 2605, mode: `MaxEncodedLen`)
	/// Storage: `AmmDex::TokenLiquidityProviders` (r:0 w:1)
	/// Proof: `AmmDex::TokenLiquidityProviders` (`max_values`: None, `max_size`: Some(84), added: 2559, mode: `MaxEncodedLen`)
	fn create_token_pool() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `553`
		//  Estimated: `6116`
		// Minimum execution time: 83_716_000 picoseconds.
		Weight::from_parts(88_573_000, 0)
			.saturating_add(Weight::from_parts(0, 6116))
			.saturating_add(T::DbWeight::get().reads(6))
			.saturating_add(T::DbWeight::get().writes(7))
	}
	/// Storage: `AmmDex::TokenPools` (r:1 w:1)
	/// Proof: `AmmDex::TokenPools` (`max_values`: None, `max_size`: Some(130), added: 2605, mode: `MaxEncodedLen`)
	/// Storage: `FungibleTokens::TokenBalances` (r:2 w:2)
	/// Proof: `FungibleTokens::TokenBalances` (`max_values`: None, `max_size`: Some(88), added: 2563, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `FungibleTokens::Tokens` (r:1 w:0)
	/// Proof: `FungibleTokens::Tokens` (`max_values`: None, `max_size`: Some(124), added: 2599, mode: `MaxEncodedLen`)
	/// Storage: `AmmDex::TokenLiquidityProviders` (r:1 w:1)
	/// Proof: `AmmDex::TokenLiquidityProviders` (`max_values`: None, `max_size`: Some(84), added: 2559, mode: `MaxEncodedLen`)
	/// The range of component `n` is `[1, 10]`.
	fn add_token_liquidity(n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `937`
		//  Estimated: `6116`
		// Minimum execution time: 86_671_000 picoseconds.
		Weight::from_parts(91_818_069, 0)
			.saturating_add(Weight::from_parts(0, 6116))
			// Standard Error: 6_649
			.saturating_add(Weight::from_parts(13_048, 0).saturating_mul(n.into()))
			.saturating_add(T::DbWeight::get().reads(6))
			.saturating_add(T::DbWeight::get().writes(5))
	}
	/// Storage: `AmmDex::TokenPools` (r:1 w:1)
	/// Proof: `AmmDex::TokenPools` (`max_values`: None, `max_size`: Some(130), added: 2605, mode: `MaxEncodedLen`)
	/// Storage: `AmmDex::TokenLiquidityProviders` (r:1 w:1)
	/// Proof: `AmmDex::TokenLiquidityProviders` (`max_values`: None, `max_size`: Some(84), added: 2559, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `FungibleTokens::Tokens` (r:1 w:0)
	/// Proof: `FungibleTokens::Tokens` (`max_values`: None, `max_size`: Some(124), added: 2599, mode: `MaxEncodedLen`)
	/// Storage: `FungibleTokens::TokenBalances` (r:2 w:2)
	/// Proof: `FungibleTokens::TokenBalances` (`max_values`: None, `max_size`: Some(88), added: 2563, mode: `MaxEncodedLen`)
	fn remove_token_liquidity() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `937`
		//  Estimated: `6116`
		// Minimum execution time: 84_768_000 picoseconds.
		Weight::from_parts(89_174_000, 0)
			.saturating_add(Weight::from_parts(0, 6116))
			.saturating_add(T::DbWeight::get().reads(6))
			.saturating_add(T::DbWeight::get().writes(5))
	}
	/// Storage: `AmmDex::TokenPools` (r:1 w:1)
	/// Proof: `AmmDex::TokenPools` (`max_values`: None, `max_size`: Some(130), added: 2605, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `FungibleTokens::Tokens` (r:1 w:0)
	/// Proof: `FungibleTokens::Tokens` (`max_values`: None, `max_size`: Some(124), added: 2599, mode: `MaxEncodedLen`)
	/// Storage: `FungibleTokens::TokenBalances` (r:2 w:2)
	/// Proof: `FungibleTokens::TokenBalances` (`max_values`: None, `max_size`: Some(88), added: 2563, mode: `MaxEncodedLen`)
	/// Storage: `AmmDex::TotalVolume` (r:1 w:1)
	/// Proof: `AmmDex::TotalVolume` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `AmmDex::TotalSwaps` (r:1 w:1)
	/// Proof: `AmmDex::TotalSwaps` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	fn swap_token() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `937`
		//  Estimated: `6116`
		// Minimum execution time: 83_756_000 picoseconds.
		Weight::from_parts(88_133_000, 0)
			.saturating_add(Weight::from_parts(0, 6116))
			.saturating_add(T::DbWeight::get().reads(7))
			.saturating_add(T::DbWeight::get().writes(6))
	}

	fn get_price() -> Weight {
		Weight::from_parts(5_000_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
	}
}
