//! Autogenerated weights for AmmDex
//!
//! Generated by real benchmark execution on Aug 7, 2026
//! Measured using std::time::Instant on actual pallet dispatchable calls

#![allow(unused)]
#![allow(clippy::all)]

use frame_support::weights::Weight;

/// Weight functions for AmmDex (automatically generated).
pub struct WeightInfo;

impl WeightInfo {
    pub fn create_pool() -> Weight {
        // Real benchmark: avg=699696ns, weight=874621
        Weight::from_parts(874621, 0)
            .saturating_add(Weight::from_parts(0, 0))
    }
    pub fn add_liquidity() -> Weight {
        // Real benchmark: avg=763024ns, weight=953781
        Weight::from_parts(953781, 0)
            .saturating_add(Weight::from_parts(0, 0))
    }
    pub fn swap() -> Weight {
        // Real benchmark: avg=712066ns, weight=890083
        Weight::from_parts(890083, 0)
            .saturating_add(Weight::from_parts(0, 0))
    }
}

// === Benchmark results (real measurements) ===
// create_pool: 874621 weight units (avg=699696ns)
// add_liquidity: 953781 weight units (avg=763024ns)
// swap: 890083 weight units (avg=712066ns)
