
//! Autogenerated weights for `pallet_amm_dex`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 58.0.0
//! DATE: 2026-08-13, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `ubuntu-32gb-nbg1-2`, CPU: `AMD EPYC-Milan Processor`
//! WASM-EXECUTION: `Compiled`, CHAIN: `Some("dev")`, DB CACHE: 1024

// Executed Command:
// ./target/release/verdis
// benchmark
// pallet
// --chain=dev
// --pallet=pallet_amm_dex
// --extrinsic=*
// --output=pallets/amm-dex/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::Weight};
use core::marker::PhantomData;

/// Weight functions for `pallet_amm_dex`.
pub struct WeightInfo<T>(PhantomData<T>);
impl<T: frame_system::Config> crate::WeightInfo for WeightInfo<T> {
	/// Storage: `AmmDex::PoolCount` (r:1 w:1)
	/// Proof: `AmmDex::PoolCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `AmmDex::PoolByPair` (r:1 w:1)
	/// Proof: `AmmDex::PoolByPair` (`max_values`: None, `max_size`: Some(86), added: 2561, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `AmmDex::Pools` (r:0 w:1)
	/// Proof: `AmmDex::Pools` (`max_values`: None, `max_size`: Some(178), added: 2653, mode: `MaxEncodedLen`)
	/// Storage: `AmmDex::LiquidityProviders` (r:0 w:1)
	/// Proof: `AmmDex::LiquidityProviders` (`max_values`: None, `max_size`: Some(84), added: 2559, mode: `MaxEncodedLen`)
	fn create_pool() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `510`
		//  Estimated: `3593`
		// Minimum execution time: 93_571_000 picoseconds.
		Weight::from_parts(100_712_000, 0)
			.saturating_add(Weight::from_parts(0, 3593))
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(5))
	}
	/// Storage: `AmmDex::Pools` (r:1 w:1)
	/// Proof: `AmmDex::Pools` (`max_values`: None, `max_size`: Some(178), added: 2653, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `AmmDex::LiquidityProviders` (r:1 w:1)
	/// Proof: `AmmDex::LiquidityProviders` (`max_values`: None, `max_size`: Some(84), added: 2559, mode: `MaxEncodedLen`)
	/// The range of component `n` is `[1, 10]`.
	fn add_liquidity(_n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `705`
		//  Estimated: `3643`
		// Minimum execution time: 94_793_000 picoseconds.
		Weight::from_parts(106_037_931, 0)
			.saturating_add(Weight::from_parts(0, 3643))
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	/// Storage: `AmmDex::Pools` (r:1 w:1)
	/// Proof: `AmmDex::Pools` (`max_values`: None, `max_size`: Some(178), added: 2653, mode: `MaxEncodedLen`)
	/// Storage: `AmmDex::LiquidityProviders` (r:1 w:1)
	/// Proof: `AmmDex::LiquidityProviders` (`max_values`: None, `max_size`: Some(84), added: 2559, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn remove_liquidity() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `705`
		//  Estimated: `3643`
		// Minimum execution time: 96_626_000 picoseconds.
		Weight::from_parts(105_389_000, 0)
			.saturating_add(Weight::from_parts(0, 3643))
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	/// Storage: `AmmDex::Pools` (r:1 w:1)
	/// Proof: `AmmDex::Pools` (`max_values`: None, `max_size`: Some(178), added: 2653, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `AmmDex::TotalVolume` (r:1 w:1)
	/// Proof: `AmmDex::TotalVolume` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `AmmDex::TotalSwaps` (r:1 w:1)
	/// Proof: `AmmDex::TotalSwaps` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	fn swap() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `633`
		//  Estimated: `3643`
		// Minimum execution time: 95_744_000 picoseconds.
		Weight::from_parts(104_738_000, 0)
			.saturating_add(Weight::from_parts(0, 3643))
			.saturating_add(T::DbWeight::get().reads(4))
			.saturating_add(T::DbWeight::get().writes(4))
	}
	/// Storage: `AmmDex::TokenPoolCount` (r:1 w:1)
	/// Proof: `AmmDex::TokenPoolCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `AmmDex::TokenPoolByPair` (r:1 w:1)
	/// Proof: `AmmDex::TokenPoolByPair` (`max_values`: None, `max_size`: Some(38), added: 2513, mode: `MaxEncodedLen`)
	/// Storage: `FungibleTokens::TokenBalances` (r:2 w:2)
	/// Proof: `FungibleTokens::TokenBalances` (`max_values`: None, `max_size`: Some(88), added: 2563, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `FungibleTokens::Tokens` (r:1 w:0)
	/// Proof: `FungibleTokens::Tokens` (`max_values`: None, `max_size`: Some(140), added: 2615, mode: `MaxEncodedLen`)
	/// Storage: `AmmDex::TokenPools` (r:0 w:1)
	/// Proof: `AmmDex::TokenPools` (`max_values`: None, `max_size`: Some(130), added: 2605, mode: `MaxEncodedLen`)
	/// Storage: `AmmDex::TokenLiquidityProviders` (r:0 w:1)
	/// Proof: `AmmDex::TokenLiquidityProviders` (`max_values`: None, `max_size`: Some(84), added: 2559, mode: `MaxEncodedLen`)
	fn create_token_pool() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `569`
		//  Estimated: `6116`
		// Minimum execution time: 82_085_000 picoseconds.
		Weight::from_parts(92_379_000, 0)
			.saturating_add(Weight::from_parts(0, 6116))
			.saturating_add(T::DbWeight::get().reads(6))
			.saturating_add(T::DbWeight::get().writes(7))
	}
	/// Storage: `AmmDex::TokenPools` (r:1 w:1)
	/// Proof: `AmmDex::TokenPools` (`max_values`: None, `max_size`: Some(130), added: 2605, mode: `MaxEncodedLen`)
	/// Storage: `FungibleTokens::TokenBalances` (r:2 w:2)
	/// Proof: `FungibleTokens::TokenBalances` (`max_values`: None, `max_size`: Some(88), added: 2563, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `FungibleTokens::Tokens` (r:1 w:0)
	/// Proof: `FungibleTokens::Tokens` (`max_values`: None, `max_size`: Some(140), added: 2615, mode: `MaxEncodedLen`)
	/// Storage: `AmmDex::TokenLiquidityProviders` (r:1 w:1)
	/// Proof: `AmmDex::TokenLiquidityProviders` (`max_values`: None, `max_size`: Some(84), added: 2559, mode: `MaxEncodedLen`)
	/// The range of component `n` is `[1, 10]`.
	fn add_token_liquidity(_n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `953`
		//  Estimated: `6116`
		// Minimum execution time: 85_639_000 picoseconds.
		Weight::from_parts(95_461_155, 0)
			.saturating_add(Weight::from_parts(0, 6116))
			.saturating_add(T::DbWeight::get().reads(6))
			.saturating_add(T::DbWeight::get().writes(5))
	}
	/// Storage: `AmmDex::TokenPools` (r:1 w:1)
	/// Proof: `AmmDex::TokenPools` (`max_values`: None, `max_size`: Some(130), added: 2605, mode: `MaxEncodedLen`)
	/// Storage: `AmmDex::TokenLiquidityProviders` (r:1 w:1)
	/// Proof: `AmmDex::TokenLiquidityProviders` (`max_values`: None, `max_size`: Some(84), added: 2559, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `FungibleTokens::Tokens` (r:1 w:0)
	/// Proof: `FungibleTokens::Tokens` (`max_values`: None, `max_size`: Some(140), added: 2615, mode: `MaxEncodedLen`)
	/// Storage: `FungibleTokens::TokenBalances` (r:2 w:2)
	/// Proof: `FungibleTokens::TokenBalances` (`max_values`: None, `max_size`: Some(88), added: 2563, mode: `MaxEncodedLen`)
	fn remove_token_liquidity() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `953`
		//  Estimated: `6116`
		// Minimum execution time: 83_706_000 picoseconds.
		Weight::from_parts(90_796_000, 0)
			.saturating_add(Weight::from_parts(0, 6116))
			.saturating_add(T::DbWeight::get().reads(6))
			.saturating_add(T::DbWeight::get().writes(5))
	}
	/// Storage: `AmmDex::TokenPools` (r:1 w:1)
	/// Proof: `AmmDex::TokenPools` (`max_values`: None, `max_size`: Some(130), added: 2605, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `FungibleTokens::Tokens` (r:1 w:0)
	/// Proof: `FungibleTokens::Tokens` (`max_values`: None, `max_size`: Some(140), added: 2615, mode: `MaxEncodedLen`)
	/// Storage: `FungibleTokens::TokenBalances` (r:2 w:2)
	/// Proof: `FungibleTokens::TokenBalances` (`max_values`: None, `max_size`: Some(88), added: 2563, mode: `MaxEncodedLen`)
	/// Storage: `AmmDex::TotalVolume` (r:1 w:1)
	/// Proof: `AmmDex::TotalVolume` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `AmmDex::TotalSwaps` (r:1 w:1)
	/// Proof: `AmmDex::TotalSwaps` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	fn swap_token() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `953`
		//  Estimated: `6116`
		// Minimum execution time: 82_584_000 picoseconds.
		Weight::from_parts(90_357_000, 0)
			.saturating_add(Weight::from_parts(0, 6116))
			.saturating_add(T::DbWeight::get().reads(7))
			.saturating_add(T::DbWeight::get().writes(6))
	}

    fn get_price() -> Weight {
        Weight::from_parts(10_000_000, 0)
    }
}
