
//! Autogenerated weights for `pallet_sealevel`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 58.0.0
//! DATE: 2026-08-13, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `ubuntu-32gb-nbg1-2`, CPU: `AMD EPYC-Milan Processor`
//! WASM-EXECUTION: `Compiled`, CHAIN: `Some("dev")`, DB CACHE: 1024

// Executed Command:
// ./target/release/verdis
// benchmark
// pallet
// --chain=dev
// --pallet=pallet_sealevel
// --extrinsic=*
// --output=pallets/sealevel/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::Weight};
use core::marker::PhantomData;

/// Weight functions for `pallet_sealevel`.
pub struct WeightInfo<T>(PhantomData<T>);
impl<T: frame_system::Config> crate::WeightInfo for WeightInfo<T> {
	/// Storage: `Sealevel::NextBatchId` (r:1 w:1)
	/// Proof: `Sealevel::NextBatchId` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Sealevel::SealevelTotalBatches` (r:1 w:1)
	/// Proof: `Sealevel::SealevelTotalBatches` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `Sealevel::SealevelParallelBatches` (r:1 w:1)
	/// Proof: `Sealevel::SealevelParallelBatches` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `Sealevel::SealevelParallelizationRate` (r:0 w:1)
	/// Proof: `Sealevel::SealevelParallelizationRate` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Sealevel::BatchParallel` (r:0 w:1)
	/// Proof: `Sealevel::BatchParallel` (`max_values`: None, `max_size`: Some(13), added: 2488, mode: `MaxEncodedLen`)
	fn create_batch() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `42`
		//  Estimated: `1493`
		// Minimum execution time: 11_628_000 picoseconds.
		Weight::from_parts(12_909_000, 0)
			.saturating_add(Weight::from_parts(0, 1493))
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(5))
	}
	/// Storage: `Sealevel::BatchParallel` (r:1 w:0)
	/// Proof: `Sealevel::BatchParallel` (`max_values`: None, `max_size`: Some(13), added: 2488, mode: `MaxEncodedLen`)
	/// Storage: `Sealevel::SealevelTotalTxs` (r:1 w:1)
	/// Proof: `Sealevel::SealevelTotalTxs` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `Sealevel::SealevelAvgComputeUnits` (r:1 w:1)
	/// Proof: `Sealevel::SealevelAvgComputeUnits` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `Sealevel::BatchComputeUnits` (r:0 w:1)
	/// Proof: `Sealevel::BatchComputeUnits` (`max_values`: None, `max_size`: Some(20), added: 2495, mode: `MaxEncodedLen`)
	fn report_execution() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `162`
		//  Estimated: `3478`
		// Minimum execution time: 13_671_000 picoseconds.
		Weight::from_parts(14_782_000, 0)
			.saturating_add(Weight::from_parts(0, 3478))
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	/// Storage: `Sealevel::SealevelConflicts` (r:1 w:1)
	/// Proof: `Sealevel::SealevelConflicts` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	fn report_conflict() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `182`
		//  Estimated: `1493`
		// Minimum execution time: 10_767_000 picoseconds.
		Weight::from_parts(12_259_000, 0)
			.saturating_add(Weight::from_parts(0, 1493))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
}
