//! Autogenerated weights for pallet_sealevel
use core::marker::PhantomData;
use frame_support::{traits::Get, weights::Weight};

/// Weight functions for pallet_sealevel.
pub trait WeightInfo {
    fn create_batch() -> Weight;
    fn report_execution() -> Weight;
    fn report_conflict() -> Weight;
}

/// Default weights using reasonable estimates.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
    fn create_batch() -> Weight {
        // Storage: read batch count, write batch entry
        Weight::from_parts(50_000, 0)
            .saturating_add(T::DbWeight::get().reads(2))
            .saturating_add(T::DbWeight::get().writes(2))
    }
    fn report_execution() -> Weight {
        // Read batch, verify, write result
        Weight::from_parts(40_000, 0)
            .saturating_add(T::DbWeight::get().reads(2))
            .saturating_add(T::DbWeight::get().writes(1))
    }
    fn report_conflict() -> Weight {
        // Read batch, write conflict
        Weight::from_parts(40_000, 0)
            .saturating_add(T::DbWeight::get().reads(2))
            .saturating_add(T::DbWeight::get().writes(1))
    }
}

impl WeightInfo for () {
    fn create_batch() -> Weight { Weight::from_parts(10_000, 0) }
    fn report_execution() -> Weight { Weight::from_parts(10_000, 0) }
    fn report_conflict() -> Weight { Weight::from_parts(10_000, 0) }
}
