//! Autogenerated weights for pallet_poh

use core::marker::PhantomData;
use frame_support::{traits::Get, weights::Weight};

pub trait WeightInfo {
    fn record_block() -> Weight;
    fn set_config() -> Weight;
    fn tick_extrinsic() -> Weight;
}

pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
    fn record_block() -> Weight {
        Weight::from_parts(10_000, 0)
            .saturating_add(T::DbWeight::get().reads(1))
            .saturating_add(T::DbWeight::get().writes(1))
    }
    fn set_config() -> Weight {
        Weight::from_parts(10_000, 0).saturating_add(T::DbWeight::get().writes(1))
    }
    fn tick_extrinsic() -> Weight {
        Weight::from_parts(10_000, 0).saturating_add(T::DbWeight::get().reads(1))
    }
}

impl WeightInfo for () {
    fn record_block() -> Weight {
        Weight::from_parts(10_000, 0)
    }
    fn set_config() -> Weight {
        Weight::from_parts(10_000, 0)
    }
    fn tick_extrinsic() -> Weight {
        Weight::from_parts(10_000, 0)
    }
}
