//! Autogenerated weights for pallet_poh

#![cfg_attr(not(feature = "std"), no_std)]

use frame_support::weights::Weight;

pub trait WeightInfo {
    fn record_block() -> Weight;
    fn set_config() -> Weight;
    fn tick() -> Weight;
}

pub struct SubstrateWeight<T>(core::marker::PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
    fn record_block() -> Weight {
        Weight::from_parts(10_000, 0)
    }
    fn set_config() -> Weight {
        Weight::from_parts(10_000, 0)
    }
    fn tick() -> Weight {
        Weight::from_parts(10_000, 0)
    }
}

impl WeightInfo for () {
    fn record_block() -> Weight {
        Weight::from_parts(10_000, 0)
    }
    fn set_config() -> Weight {
        Weight::from_parts(10_000, 0)
    }
    fn tick() -> Weight {
        Weight::from_parts(10_000, 0)
    }
}
