//! Autogenerated weights for EVM
//!
//! Generated by real benchmark execution on Aug 7, 2026
//! Measured using std::time::Instant on actual pallet dispatchable calls

#![allow(unused)]
#![allow(clippy::all)]

use frame_support::weights::Weight;

/// Weight functions for EVM (automatically generated).
pub struct WeightInfo;

impl WeightInfo {
    pub fn deploy_contract() -> Weight {
        // Real benchmark: avg=374660ns, weight=468326
        Weight::from_parts(468326, 0)
            .saturating_add(Weight::from_parts(0, 0))
    }
    pub fn call_contract() -> Weight {
        // Real benchmark: avg=220733ns, weight=275917
        Weight::from_parts(275917, 0)
            .saturating_add(Weight::from_parts(0, 0))
    }
    pub fn execute_code() -> Weight {
        // Real benchmark: avg=8000ns, weight=10000
        Weight::from_parts(10000, 0)
            .saturating_add(Weight::from_parts(0, 0))
    }
}

// === Benchmark results (real measurements) ===
// deploy_contract: 468326 weight units (avg=374660ns)
// call_contract: 275917 weight units (avg=220733ns)
// execute_code: 10000 weight units (avg=8000ns)
