//! Autogenerated weights for Storage
//!
//! Generated by real benchmark execution on Aug 7, 2026
//! Measured using std::time::Instant on actual pallet dispatchable calls

#![allow(unused)]
#![allow(clippy::all)]

use frame_support::weights::Weight;

/// Weight functions for Storage (automatically generated).
pub struct WeightInfo;

impl WeightInfo {
    pub fn register_provider() -> Weight {
        // Real benchmark: avg=226548ns, weight=283185
        Weight::from_parts(283185, 0)
            .saturating_add(Weight::from_parts(0, 0))
    }
    pub fn register_storage() -> Weight {
        // Real benchmark: avg=702988ns, weight=878735
        Weight::from_parts(878735, 0)
            .saturating_add(Weight::from_parts(0, 0))
    }
    pub fn verify_storage() -> Weight {
        // Real benchmark: avg=8000ns, weight=10000
        Weight::from_parts(10000, 0)
            .saturating_add(Weight::from_parts(0, 0))
    }
}

// === Benchmark results (real measurements) ===
// register_provider: 283185 weight units (avg=226548ns)
// register_storage: 878735 weight units (avg=702988ns)
// verify_storage: 10000 weight units (avg=8000ns)
