//! Autogenerated weights for pallet_ibc
use core::marker::PhantomData;
use frame_support::{traits::Get, weights::Weight};

/// Weight functions for pallet_ibc.
pub trait WeightInfo {
    fn create_client() -> Weight;
    fn open_connection() -> Weight;
    fn open_channel() -> Weight;
    fn send_packet() -> Weight;
    fn recv_packet() -> Weight;
    fn acknowledge_packet() -> Weight;
    fn timeout_packet() -> Weight;
    fn transfer() -> Weight;
    fn close_channel() -> Weight;
    fn update_client() -> Weight;
}

/// Default weights using reasonable estimates.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
    fn create_client() -> Weight {
        Weight::from_parts(10_000, 0)
            .saturating_add(T::DbWeight::get().reads(1))
            .saturating_add(T::DbWeight::get().writes(1))
    }
    fn open_connection() -> Weight {
        Weight::from_parts(15_000, 0)
            .saturating_add(T::DbWeight::get().reads(2))
            .saturating_add(T::DbWeight::get().writes(1))
    }
    fn open_channel() -> Weight {
        Weight::from_parts(15_000, 0)
            .saturating_add(T::DbWeight::get().reads(2))
            .saturating_add(T::DbWeight::get().writes(1))
    }
    fn send_packet() -> Weight {
        Weight::from_parts(20_000, 0)
            .saturating_add(T::DbWeight::get().reads(2))
            .saturating_add(T::DbWeight::get().writes(2))
    }
    fn recv_packet() -> Weight {
        Weight::from_parts(20_000, 0)
            .saturating_add(T::DbWeight::get().reads(3))
            .saturating_add(T::DbWeight::get().writes(2))
    }
    fn acknowledge_packet() -> Weight {
        Weight::from_parts(15_000, 0)
            .saturating_add(T::DbWeight::get().reads(2))
            .saturating_add(T::DbWeight::get().writes(1))
    }
    fn timeout_packet() -> Weight {
        Weight::from_parts(15_000, 0)
            .saturating_add(T::DbWeight::get().reads(2))
            .saturating_add(T::DbWeight::get().writes(1))
    }
    fn transfer() -> Weight {
        Weight::from_parts(25_000, 0)
            .saturating_add(T::DbWeight::get().reads(3))
            .saturating_add(T::DbWeight::get().writes(3))
    }
    fn close_channel() -> Weight {
        Weight::from_parts(10_000, 0)
            .saturating_add(T::DbWeight::get().reads(1))
            .saturating_add(T::DbWeight::get().writes(1))
    }
    fn update_client() -> Weight {
        Weight::from_parts(10_000, 0)
            .saturating_add(T::DbWeight::get().reads(2))
            .saturating_add(T::DbWeight::get().writes(1))
    }
}

impl WeightInfo for () {
    fn create_client() -> Weight { Weight::from_parts(10_000, 0) }
    fn open_connection() -> Weight { Weight::from_parts(10_000, 0) }
    fn open_channel() -> Weight { Weight::from_parts(10_000, 0) }
    fn send_packet() -> Weight { Weight::from_parts(10_000, 0) }
    fn recv_packet() -> Weight { Weight::from_parts(10_000, 0) }
    fn acknowledge_packet() -> Weight { Weight::from_parts(10_000, 0) }
    fn timeout_packet() -> Weight { Weight::from_parts(10_000, 0) }
    fn transfer() -> Weight { Weight::from_parts(10_000, 0) }
    fn close_channel() -> Weight { Weight::from_parts(10_000, 0) }
    fn update_client() -> Weight { Weight::from_parts(10_000, 0) }
}
