
//! Autogenerated weights for `pallet_vesting`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 58.0.0
//! DATE: 2026-08-09, STEPS: `20`, REPEAT: `10`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `ubuntu-32gb-nbg1-2`, CPU: `AMD EPYC-Milan Processor`
//! WASM-EXECUTION: `Compiled`, CHAIN: `Some("dev")`, DB CACHE: 1024

// Executed Command:
// ./target/release/verdis
// benchmark
// pallet
// --chain
// dev
// --pallet
// pallet_vesting
// --extrinsic
// *
// --steps
// 20
// --repeat
// 10
// --output
// /tmp/weights_vesting.rs
// --template
// node/src/weight-template.hbs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::Weight};
use core::marker::PhantomData;

/// Weight functions for `pallet_vesting`.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> crate::WeightInfo for SubstrateWeight<T> {
	/// Storage: `Vesting::Schedules` (r:1 w:1)
	/// Proof: `Vesting::Schedules` (`max_values`: None, `max_size`: Some(172), added: 2647, mode: `MaxEncodedLen`)
	/// The range of component `s` is `[1, 64]`.
	fn add_schedule(s: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `205`
		//  Estimated: `3637`
		// Minimum execution time: 12_809_000 picoseconds.
		Weight::from_parts(14_586_545, 0)
			.saturating_add(Weight::from_parts(0, 3637))
			// Standard Error: 187
			.saturating_add(Weight::from_parts(8_970, 0).saturating_mul(s.into()))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `Vesting::Schedules` (r:1 w:0)
	/// Proof: `Vesting::Schedules` (`max_values`: None, `max_size`: Some(172), added: 2647, mode: `MaxEncodedLen`)
	/// Storage: `Vesting::UserVestings` (r:1 w:1)
	/// Proof: `Vesting::UserVestings` (`max_values`: None, `max_size`: Some(1937), added: 4412, mode: `MaxEncodedLen`)
	/// Storage: `Vesting::LockedBalances` (r:1 w:1)
	/// Proof: `Vesting::LockedBalances` (`max_values`: None, `max_size`: Some(64), added: 2539, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Locks` (r:1 w:1)
	/// Proof: `Balances::Locks` (`max_values`: None, `max_size`: Some(1299), added: 3774, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Freezes` (r:1 w:0)
	/// Proof: `Balances::Freezes` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// The range of component `s` is `[1, 15]`.
	fn assign_vesting(s: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `468 + s * (72 ±0)`
		//  Estimated: `5402`
		// Minimum execution time: 47_311_000 picoseconds.
		Weight::from_parts(50_470_183, 0)
			.saturating_add(Weight::from_parts(0, 5402))
			// Standard Error: 2_345
			.saturating_add(Weight::from_parts(283_926, 0).saturating_mul(s.into()))
			.saturating_add(T::DbWeight::get().reads(6))
			.saturating_add(T::DbWeight::get().writes(4))
	}
	/// Storage: `Vesting::UserVestings` (r:1 w:1)
	/// Proof: `Vesting::UserVestings` (`max_values`: None, `max_size`: Some(1937), added: 4412, mode: `MaxEncodedLen`)
	/// Storage: `Vesting::Schedules` (r:1 w:0)
	/// Proof: `Vesting::Schedules` (`max_values`: None, `max_size`: Some(172), added: 2647, mode: `MaxEncodedLen`)
	/// Storage: `Vesting::LockedBalances` (r:1 w:1)
	/// Proof: `Vesting::LockedBalances` (`max_values`: None, `max_size`: Some(64), added: 2539, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Locks` (r:1 w:1)
	/// Proof: `Balances::Locks` (`max_values`: None, `max_size`: Some(1299), added: 3774, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Freezes` (r:1 w:0)
	/// Proof: `Balances::Freezes` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	/// The range of component `s` is `[1, 16]`.
	fn release_vested(s: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `508 + s * (69 ±0)`
		//  Estimated: `5402`
		// Minimum execution time: 50_636_000 picoseconds.
		Weight::from_parts(49_170_981, 0)
			.saturating_add(Weight::from_parts(0, 5402))
			// Standard Error: 3_692
			.saturating_add(Weight::from_parts(4_500_500, 0).saturating_mul(s.into()))
			.saturating_add(T::DbWeight::get().reads(5))
			.saturating_add(T::DbWeight::get().writes(3))
	}
}
