//! Autogenerated weights for Vesting
//!
//! Generated by real benchmark execution on Aug 7, 2026
//! Measured using std::time::Instant on actual pallet dispatchable calls

#![allow(unused)]
#![allow(clippy::all)]

use frame_support::weights::Weight;

/// Weight functions for Vesting (automatically generated).
pub struct WeightInfo;

impl WeightInfo {
    pub fn assign_vesting() -> Weight {
        // Real benchmark: avg=363764ns, weight=454705
        Weight::from_parts(454705, 0)
            .saturating_add(Weight::from_parts(0, 0))
    }
    pub fn release_vested() -> Weight {
        // Real benchmark: avg=8000ns, weight=10000
        Weight::from_parts(10000, 0)
            .saturating_add(Weight::from_parts(0, 0))
    }
}

// === Benchmark results (real measurements) ===
// assign_vesting: 454705 weight units (avg=363764ns)
// release_vested: 10000 weight units (avg=8000ns)
