
//! Autogenerated weights for `pallet_tokenomics`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 58.0.0
//! DATE: 2026-08-13, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `ubuntu-32gb-nbg1-2`, CPU: `AMD EPYC-Milan Processor`
//! WASM-EXECUTION: `Compiled`, CHAIN: `Some("dev")`, DB CACHE: 1024

// Executed Command:
// ./target/release/verdis
// benchmark
// pallet
// --chain=dev
// --pallet=pallet_tokenomics
// --extrinsic=*
// --output=pallets/tokenomics/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::Weight};
use core::marker::PhantomData;

/// Weight functions for `pallet_tokenomics`.
pub struct WeightInfo<T>(PhantomData<T>);
impl<T: frame_system::Config> crate::WeightInfo for WeightInfo<T> {
	/// Storage: `Tokenomics::ConsentGiven` (r:1 w:1)
	/// Proof: `Tokenomics::ConsentGiven` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	fn give_consent() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `170`
		//  Estimated: `3514`
		// Minimum execution time: 10_806_000 picoseconds.
		Weight::from_parts(12_980_000, 0)
			.saturating_add(Weight::from_parts(0, 3514))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `Tokenomics::ConsentGiven` (r:1 w:0)
	/// Proof: `Tokenomics::ConsentGiven` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	/// Storage: `Tokenomics::PresaleSold` (r:1 w:1)
	/// Proof: `Tokenomics::PresaleSold` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `Tokenomics::PresalePrice` (r:1 w:0)
	/// Proof: `Tokenomics::PresalePrice` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Tokenomics::PresaleRaised` (r:1 w:1)
	/// Proof: `Tokenomics::PresaleRaised` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `Tokenomics::CirculatingSupply` (r:1 w:1)
	/// Proof: `Tokenomics::CirculatingSupply` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	fn purchase() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `492`
		//  Estimated: `3593`
		// Minimum execution time: 93_590_000 picoseconds.
		Weight::from_parts(99_360_000, 0)
			.saturating_add(Weight::from_parts(0, 3593))
			.saturating_add(T::DbWeight::get().reads(6))
			.saturating_add(T::DbWeight::get().writes(4))
	}
	/// Storage: `Tokenomics::PresalePrice` (r:0 w:1)
	/// Proof: `Tokenomics::PresalePrice` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	fn update_presale_price() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 4_627_000 picoseconds.
		Weight::from_parts(5_538_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `Tokenomics::Distribution` (r:1 w:1)
	/// Proof: `Tokenomics::Distribution` (`max_values`: None, `max_size`: Some(123), added: 2598, mode: `MaxEncodedLen`)
	/// Storage: `Tokenomics::CirculatingSupply` (r:1 w:1)
	/// Proof: `Tokenomics::CirculatingSupply` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	fn release_distribution() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `277`
		//  Estimated: `3588`
		// Minimum execution time: 14_382_000 picoseconds.
		Weight::from_parts(16_365_000, 0)
			.saturating_add(Weight::from_parts(0, 3588))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(2))
	}
}
