//! Autogenerated weights for DPoS
//!
//! Generated by real benchmark execution on Aug 7, 2026
//! Measured using std::time::Instant on actual pallet dispatchable calls

#![allow(unused)]
#![allow(clippy::all)]

use frame_support::weights::Weight;

/// Weight functions for DPoS (automatically generated).
pub struct WeightInfo;

impl WeightInfo {
    pub fn register_validator() -> Weight {
        // Real benchmark: avg=327334ns, weight=409168
        Weight::from_parts(409168, 0)
            .saturating_add(Weight::from_parts(0, 0))
    }
    pub fn vote() -> Weight {
        // Real benchmark: avg=564430ns, weight=705538
        Weight::from_parts(705538, 0)
            .saturating_add(Weight::from_parts(0, 0))
    }
    pub fn update_green_score() -> Weight {
        // Real benchmark: avg=79260ns, weight=99076
        Weight::from_parts(99076, 0)
            .saturating_add(Weight::from_parts(0, 0))
    }
}

// === Benchmark results (real measurements) ===
// register_validator: 409168 weight units (avg=327334ns)
// vote: 705538 weight units (avg=564430ns)
// update_green_score: 99076 weight units (avg=79260ns)
