
//! Autogenerated weights for `pallet_dpos`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 58.0.0
//! DATE: 2026-08-09, STEPS: `20`, REPEAT: `10`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `ubuntu-32gb-nbg1-2`, CPU: `AMD EPYC-Milan Processor`
//! WASM-EXECUTION: `Compiled`, CHAIN: `Some("dev")`, DB CACHE: 1024

// Executed Command:
// ./target/release/verdis
// benchmark
// pallet
// --chain
// dev
// --pallet
// pallet_dpos
// --extrinsic
// *
// --steps
// 20
// --repeat
// 10
// --output
// /tmp/weights_dpos.rs
// --template
// node/src/weight-template.hbs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::Weight};
use core::marker::PhantomData;

/// Weight functions for `pallet_dpos`.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> crate::WeightInfo for SubstrateWeight<T> {
	/// Storage: `Dpos::Validators` (r:1 w:1)
	/// Proof: `Dpos::Validators` (`max_values`: None, `max_size`: Some(205), added: 2680, mode: `MaxEncodedLen`)
	/// Storage: `Dpos::ValidatorList` (r:1 w:1)
	/// Proof: `Dpos::ValidatorList` (`max_values`: Some(1), `max_size`: Some(32034), added: 32529, mode: `MaxEncodedLen`)
	/// Storage: `Dpos::TotalStaked` (r:1 w:1)
	/// Proof: `Dpos::TotalStaked` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	fn register_validator() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `617`
		//  Estimated: `33519`
		// Minimum execution time: 39_689_000 picoseconds.
		Weight::from_parts(42_684_000, 0)
			.saturating_add(Weight::from_parts(0, 33519))
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	/// Storage: `Dpos::Validators` (r:1 w:1)
	/// Proof: `Dpos::Validators` (`max_values`: None, `max_size`: Some(205), added: 2680, mode: `MaxEncodedLen`)
	/// Storage: `Dpos::ValidatorList` (r:1 w:1)
	/// Proof: `Dpos::ValidatorList` (`max_values`: Some(1), `max_size`: Some(32034), added: 32529, mode: `MaxEncodedLen`)
	/// Storage: `Dpos::ActiveValidators` (r:1 w:1)
	/// Proof: `Dpos::ActiveValidators` (`max_values`: Some(1), `max_size`: Some(32034), added: 32529, mode: `MaxEncodedLen`)
	/// Storage: `Dpos::TotalStaked` (r:1 w:1)
	/// Proof: `Dpos::TotalStaked` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	fn unregister_validator() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `997`
		//  Estimated: `33519`
		// Minimum execution time: 38_818_000 picoseconds.
		Weight::from_parts(41_312_000, 0)
			.saturating_add(Weight::from_parts(0, 33519))
			.saturating_add(T::DbWeight::get().reads(4))
			.saturating_add(T::DbWeight::get().writes(4))
	}
	/// Storage: `Dpos::Validators` (r:1 w:1)
	/// Proof: `Dpos::Validators` (`max_values`: None, `max_size`: Some(205), added: 2680, mode: `MaxEncodedLen`)
	/// Storage: `Dpos::Votes` (r:1 w:1)
	/// Proof: `Dpos::Votes` (`max_values`: None, `max_size`: Some(10290), added: 12765, mode: `MaxEncodedLen`)
	/// Storage: `Dpos::TotalStaked` (r:1 w:1)
	/// Proof: `Dpos::TotalStaked` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	fn vote() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `595`
		//  Estimated: `13755`
		// Minimum execution time: 41_863_000 picoseconds.
		Weight::from_parts(44_798_000, 0)
			.saturating_add(Weight::from_parts(0, 13755))
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	/// Storage: `Dpos::Validators` (r:1 w:1)
	/// Proof: `Dpos::Validators` (`max_values`: None, `max_size`: Some(205), added: 2680, mode: `MaxEncodedLen`)
	/// Storage: `Dpos::Votes` (r:1 w:1)
	/// Proof: `Dpos::Votes` (`max_values`: None, `max_size`: Some(10290), added: 12765, mode: `MaxEncodedLen`)
	/// Storage: `Dpos::TotalStaked` (r:1 w:1)
	/// Proof: `Dpos::TotalStaked` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `Dpos::UnbondingQueue` (r:1 w:1)
	/// Proof: `Dpos::UnbondingQueue` (`max_values`: None, `max_size`: Some(10802), added: 13277, mode: `MaxEncodedLen`)
	fn unvote() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `749`
		//  Estimated: `14267`
		// Minimum execution time: 29_494_000 picoseconds.
		Weight::from_parts(32_088_000, 0)
			.saturating_add(Weight::from_parts(0, 14267))
			.saturating_add(T::DbWeight::get().reads(4))
			.saturating_add(T::DbWeight::get().writes(4))
	}
	/// Storage: `Dpos::UnbondingQueue` (r:1 w:1)
	/// Proof: `Dpos::UnbondingQueue` (`max_values`: None, `max_size`: Some(10802), added: 13277, mode: `MaxEncodedLen`)
	fn withdraw_unbonded() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `369`
		//  Estimated: `14267`
		// Minimum execution time: 26_871_000 picoseconds.
		Weight::from_parts(30_045_000, 0)
			.saturating_add(Weight::from_parts(0, 14267))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `Dpos::Validators` (r:1 w:1)
	/// Proof: `Dpos::Validators` (`max_values`: None, `max_size`: Some(205), added: 2680, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Dpos::SlashingEvents` (r:1 w:1)
	/// Proof: `Dpos::SlashingEvents` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `Dpos::TotalStaked` (r:1 w:1)
	/// Proof: `Dpos::TotalStaked` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `Dpos::ActiveValidators` (r:1 w:1)
	/// Proof: `Dpos::ActiveValidators` (`max_values`: Some(1), `max_size`: Some(32034), added: 32529, mode: `MaxEncodedLen`)
	fn slash_validator() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `984`
		//  Estimated: `33519`
		// Minimum execution time: 78_689_000 picoseconds.
		Weight::from_parts(84_287_000, 0)
			.saturating_add(Weight::from_parts(0, 33519))
			.saturating_add(T::DbWeight::get().reads(6))
			.saturating_add(T::DbWeight::get().writes(6))
	}
	/// Storage: `Dpos::Validators` (r:1 w:1)
	/// Proof: `Dpos::Validators` (`max_values`: None, `max_size`: Some(205), added: 2680, mode: `MaxEncodedLen`)
	fn update_green_score() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `570`
		//  Estimated: `3670`
		// Minimum execution time: 15_593_000 picoseconds.
		Weight::from_parts(17_406_000, 0)
			.saturating_add(Weight::from_parts(0, 3670))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
}
