#!/usr/bin/env bash
# Add WeightInfo traits to turbine, sealevel, ibc, poh pallets
# and wire them into the runtime config
set -e

cd /opt/verdis-chain-rust

# ============ TURBINE ============
cat > pallets/turbine/src/weights.rs << 'RUST'
//! Autogenerated weights for pallet_turbine
use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions for pallet_turbine.
pub trait WeightInfo {
    fn register_shard() -> Weight;
    fn rebuild_tree(v: u32) -> Weight;
    fn mark_block_propagated() -> Weight;
}

/// Default weights using reasonable estimates.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
    fn register_shard() -> Weight {
        // Storage: read shard count, write shard entry
        Weight::from_parts(50_000, 0)
            .saturating_add(T::DbWeight::get().reads(1))
            .saturating_add(T::DbWeight::get().writes(1))
    }
    fn rebuild_tree(v: u32) -> Weight {
        // O(n) tree rebuild over validators
        Weight::from_parts(20_000, 0)
            .saturating_add(Weight::from_parts(2_000, 0).saturating_mul(v.into()))
            .saturating_add(T::DbWeight::get().reads(1))
            .saturating_add(T::DbWeight::get().writes(1))
    }
    fn mark_block_propagated() -> Weight {
        // Simple storage write
        Weight::from_parts(20_000, 0)
            .saturating_add(T::DbWeight::get().reads(1))
            .saturating_add(T::DbWeight::get().writes(1))
    }
}
RUST

# Add weights module to turbine lib.rs
python3 << 'PYEOF'
with open('pallets/turbine/src/lib.rs', 'r') as f:
    content = f.read()

# Add pub mod weights if not exists
if 'pub mod weights' not in content:
    # Add after the first use statement
    content = content.replace(
        '#[cfg_attr(not(feature = "std"), no_std)]',
        '#[cfg_attr(not(feature = "std"), no_std)]\npub mod weights;\nuse weights::WeightInfo;',
        1
    )

# Add type WeightInfo to Config trait
if 'type WeightInfo' not in content.split('pub enum Event')[0] if 'pub enum Event' in content else True:
    # Find the Config trait and add WeightInfo
    content = content.replace(
        'pub trait Config: frame_system::Config {',
        'pub trait Config: frame_system::Config {\n\t\ttype WeightInfo: WeightInfo;',
        1
    )

# Replace weight(0) with WeightInfo calls
content = content.replace(
    '#[pallet::weight(0)]\n        pub fn register_shard(',
    '#[pallet::weight(T::WeightInfo::register_shard())]\n        pub fn register_shard('
)
content = content.replace(
    '#[pallet::weight(0)]\n        pub fn rebuild_tree(',
    '#[pallet::weight(T::WeightInfo::rebuild_tree(validator_count))]\n        pub fn rebuild_tree('
)
content = content.replace(
    '#[pallet::weight(0)]\n        pub fn mark_block_propagated(',
    '#[pallet::weight(T::WeightInfo::mark_block_propagated())]\n        pub fn mark_block_propagated('
)

with open('pallets/turbine/src/lib.rs', 'w') as f:
    f.write(content)
print("TURBINE: WeightInfo added")
PYEOF

# ============ SEALEVEL ============
cat > pallets/sealevel/src/weights.rs << 'RUST'
//! Autogenerated weights for pallet_sealevel
use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions for pallet_sealevel.
pub trait WeightInfo {
    fn create_batch() -> Weight;
    fn report_execution() -> Weight;
    fn report_conflict() -> Weight;
}

/// Default weights using reasonable estimates.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
    fn create_batch() -> Weight {
        // Storage: read batch count, write batch entry
        Weight::from_parts(50_000, 0)
            .saturating_add(T::DbWeight::get().reads(2))
            .saturating_add(T::DbWeight::get().writes(2))
    }
    fn report_execution() -> Weight {
        // Read batch, verify, write result
        Weight::from_parts(40_000, 0)
            .saturating_add(T::DbWeight::get().reads(2))
            .saturating_add(T::DbWeight::get().writes(1))
    }
    fn report_conflict() -> Weight {
        // Read batch, write conflict
        Weight::from_parts(40_000, 0)
            .saturating_add(T::DbWeight::get().reads(2))
            .saturating_add(T::DbWeight::get().writes(1))
    }
}
RUST

python3 << 'PYEOF'
with open('pallets/sealevel/src/lib.rs', 'r') as f:
    content = f.read()

if 'pub mod weights' not in content:
    content = content.replace(
        '#[cfg_attr(not(feature = "std"), no_std)]',
        '#[cfg_attr(not(feature = "std"), no_std)]\npub mod weights;\nuse weights::WeightInfo;',
        1
    )

content = content.replace(
    'pub trait Config: frame_system::Config {',
    'pub trait Config: frame_system::Config {\n\t\ttype WeightInfo: WeightInfo;',
    1
)

content = content.replace(
    '#[pallet::weight(0)]\n        pub fn create_batch(',
    '#[pallet::weight(T::WeightInfo::create_batch())]\n        pub fn create_batch('
)
content = content.replace(
    '#[pallet::weight(0)]\n        pub fn report_execution(',
    '#[pallet::weight(T::WeightInfo::report_execution())]\n        pub fn report_execution('
)
content = content.replace(
    '#[pallet::weight(0)]\n        pub fn report_conflict(',
    '#[pallet::weight(T::WeightInfo::report_conflict())]\n        pub fn report_conflict('
)

with open('pallets/sealevel/src/lib.rs', 'w') as f:
    f.write(content)
print("SEALEVEL: WeightInfo added")
PYEOF

# ============ IBC ============
cat > pallets/ibc/src/weights.rs << 'RUST'
//! Autogenerated weights for pallet_ibc
use frame_support::{traits::Get, weights::{Weight}};
use core::marker::PhantomData;

/// Weight functions for pallet_ibc.
pub trait WeightInfo {
    fn create_client() -> Weight;
    fn open_connection() -> Weight;
    fn open_channel() -> Weight;
    fn send_packet() -> Weight;
    fn recv_packet() -> Weight;
    fn acknowledge_packet() -> Weight;
    fn timeout_packet() -> Weight;
    fn transfer() -> Weight;
    fn close_channel() -> Weight;
    fn update_client() -> Weight;
}

/// Default weights using reasonable estimates.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
    fn create_client() -> Weight {
        Weight::from_parts(10_000, 0)
            .saturating_add(T::DbWeight::get().reads(1))
            .saturating_add(T::DbWeight::get().writes(1))
    }
    fn open_connection() -> Weight {
        Weight::from_parts(15_000, 0)
            .saturating_add(T::DbWeight::get().reads(2))
            .saturating_add(T::DbWeight::get().writes(1))
    }
    fn open_channel() -> Weight {
        Weight::from_parts(15_000, 0)
            .saturating_add(T::DbWeight::get().reads(2))
            .saturating_add(T::DbWeight::get().writes(1))
    }
    fn send_packet() -> Weight {
        Weight::from_parts(20_000, 0)
            .saturating_add(T::DbWeight::get().reads(2))
            .saturating_add(T::DbWeight::get().writes(2))
    }
    fn recv_packet() -> Weight {
        Weight::from_parts(20_000, 0)
            .saturating_add(T::DbWeight::get().reads(3))
            .saturating_add(T::DbWeight::get().writes(2))
    }
    fn acknowledge_packet() -> Weight {
        Weight::from_parts(15_000, 0)
            .saturating_add(T::DbWeight::get().reads(2))
            .saturating_add(T::DbWeight::get().writes(1))
    }
    fn timeout_packet() -> Weight {
        Weight::from_parts(15_000, 0)
            .saturating_add(T::DbWeight::get().reads(2))
            .saturating_add(T::DbWeight::get().writes(1))
    }
    fn transfer() -> Weight {
        Weight::from_parts(25_000, 0)
            .saturating_add(T::DbWeight::get().reads(3))
            .saturating_add(T::DbWeight::get().writes(3))
    }
    fn close_channel() -> Weight {
        Weight::from_parts(10_000, 0)
            .saturating_add(T::DbWeight::get().reads(1))
            .saturating_add(T::DbWeight::get().writes(1))
    }
    fn update_client() -> Weight {
        Weight::from_parts(10_000, 0)
            .saturating_add(T::DbWeight::get().reads(2))
            .saturating_add(T::DbWeight::get().writes(1))
    }
}
RUST

python3 << 'PYEOF'
with open('pallets/ibc/src/lib.rs', 'r') as f:
    content = f.read()

if 'pub mod weights' not in content:
    content = content.replace(
        '#[cfg_attr(not(feature = "std"), no_std)]',
        '#[cfg_attr(not(feature = "std"), no_std)]\npub mod weights;\nuse weights::WeightInfo;',
        1
    )

content = content.replace(
    'pub trait Config: frame_system::Config {',
    'pub trait Config: frame_system::Config {\n\t\ttype WeightInfo: WeightInfo;',
    1
)

# Replace hardcoded weights with WeightInfo calls
content = content.replace(
    "#[pallet::weight(Weight::from_parts(10_000, 0))]\n        pub fn create_client(",
    "#[pallet::weight(T::WeightInfo::create_client())]\n        pub fn create_client("
)
content = content.replace(
    "#[pallet::weight(Weight::from_parts(15_000, 0))]\n        pub fn open_connection(",
    "#[pallet::weight(T::WeightInfo::open_connection())]\n        pub fn open_connection("
)
content = content.replace(
    "#[pallet::weight(Weight::from_parts(15_000, 0))]\n        pub fn open_channel(",
    "#[pallet::weight(T::WeightInfo::open_channel())]\n        pub fn open_channel("
)
content = content.replace(
    "#[pallet::weight(Weight::from_parts(20_000, 0))]\n        pub fn send_packet(",
    "#[pallet::weight(T::WeightInfo::send_packet())]\n        pub fn send_packet("
)
content = content.replace(
    "#[pallet::weight(Weight::from_parts(20_000, 0))]\n        pub fn recv_packet(",
    "#[pallet::weight(T::WeightInfo::recv_packet())]\n        pub fn recv_packet("
)
content = content.replace(
    "#[pallet::weight(Weight::from_parts(15_000, 0))]\n        pub fn acknowledge_packet(",
    "#[pallet::weight(T::WeightInfo::acknowledge_packet())]\n        pub fn acknowledge_packet("
)
content = content.replace(
    "#[pallet::weight(Weight::from_parts(15_000, 0))]\n        pub fn timeout_packet(",
    "#[pallet::weight(T::WeightInfo::timeout_packet())]\n        pub fn timeout_packet("
)
content = content.replace(
    "#[pallet::weight(Weight::from_parts(25_000, 0))]\n        pub fn transfer(",
    "#[pallet::weight(T::WeightInfo::transfer())]\n        pub fn transfer("
)
content = content.replace(
    "#[pallet::weight(Weight::from_parts(10_000, 0))]\n        pub fn close_channel(",
    "#[pallet::weight(T::WeightInfo::close_channel())]\n        pub fn close_channel("
)
content = content.replace(
    "#[pallet::weight(Weight::from_parts(10_000, 0))]\n        pub fn update_client(",
    "#[pallet::weight(T::WeightInfo::update_client())]\n        pub fn update_client("
)

with open('pallets/ibc/src/lib.rs', 'w') as f:
    f.write(content)
print("IBC: WeightInfo added")
PYEOF

# ============ POH ============
# PoH already has WeightInfo trait defined, just need to add to Config and runtime
python3 << 'PYEOF'
with open('pallets/poh/src/lib.rs', 'r') as f:
    content = f.read()

# Check if WeightInfo is already in Config
config_section = content.split('pub trait Config: frame_system::Config {')
if len(config_section) > 1:
    config_body = config_section[1].split('}')[0]
    if 'type WeightInfo' not in config_body:
        content = content.replace(
            'pub trait Config: frame_system::Config {',
            'pub trait Config: frame_system::Config {\n\t\ttype WeightInfo: WeightInfo;',
            1
        )
        print("POH: WeightInfo added to Config")
    else:
        print("POH: WeightInfo already in Config")
else:
    print("POH: Config trait not found in expected format")

# Replace hardcoded weights with WeightInfo calls
content = content.replace(
    '#[pallet::weight(Weight::from_parts(10_000, 0))]\n        pub fn record_block(',
    '#[pallet::weight(T::WeightInfo::record_block())]\n        pub fn record_block('
)
content = content.replace(
    '#[pallet::weight(Weight::from_parts(10_000, 0))]\n        pub fn set_config(',
    '#[pallet::weight(T::WeightInfo::set_config())]\n        pub fn set_config('
)
content = content.replace(
    '#[pallet::weight(Weight::from_parts(10_000, 0))]\n        pub fn tick_extrinsic(',
    '#[pallet::weight(T::WeightInfo::tick_extrinsic())]\n        pub fn tick_extrinsic('
)

with open('pallets/poh/src/lib.rs', 'w') as f:
    f.write(content)
print("POH: WeightInfo weights applied")
PYEOF

# ============ RUNTIME CONFIG ============
python3 << 'PYEOF'
with open('runtime/src/lib.rs', 'r') as f:
    content = f.read()

# Add WeightInfo to runtime config for each pallet
# Find the Config impl blocks and add WeightInfo

# Turbine
if 'pallet_turbine::SubstrateWeight<Runtime>' not in content:
    # Find the turbine Config impl
    import re
    turbine_match = re.search(r'(impl pallet_turbine::Config for Runtime \{[^}]+)', content)
    if turbine_match:
        old = turbine_match.group(1)
        if 'type WeightInfo' not in old:
            new = old.rstrip() + '\n    type WeightInfo = pallet_turbine::SubstrateWeight<Runtime>;'
            content = content.replace(old, new)
            print("RUNTIME: Turbine WeightInfo added")

# Sealevel
if 'pallet_sealevel::SubstrateWeight<Runtime>' not in content:
    sealevel_match = re.search(r'(impl pallet_sealevel::Config for Runtime \{[^}]+)', content)
    if sealevel_match:
        old = sealevel_match.group(1)
        if 'type WeightInfo' not in old:
            new = old.rstrip() + '\n    type WeightInfo = pallet_sealevel::SubstrateWeight<Runtime>;'
            content = content.replace(old, new)
            print("RUNTIME: Sealevel WeightInfo added")

# IBC
if 'pallet_ibc::SubstrateWeight<Runtime>' not in content:
    ibc_match = re.search(r'(impl pallet_ibc::Config for Runtime \{[^}]+)', content)
    if ibc_match:
        old = ibc_match.group(1)
        if 'type WeightInfo' not in old:
            new = old.rstrip() + '\n    type WeightInfo = pallet_ibc::SubstrateWeight<Runtime>;'
            content = content.replace(old, new)
            print("RUNTIME: IBC WeightInfo added")

# PoH
if 'pallet_poh::SubstrateWeight<Runtime>' not in content:
    poh_match = re.search(r'(impl pallet_poh::Config for Runtime \{[^}]+)', content)
    if poh_match:
        old = poh_match.group(1)
        if 'type WeightInfo' not in old:
            new = old.rstrip() + '\n    type WeightInfo = pallet_poh::SubstrateWeight<Runtime>;'
            content = content.replace(old, new)
            print("RUNTIME: PoH WeightInfo added")

with open('runtime/src/lib.rs', 'w') as f:
    f.write(content)
print("RUNTIME: All WeightInfo configs updated")
PYEOF

echo ""
echo "=== WEIGHTINFO INTEGRATION COMPLETE ==="
echo "Pallets modified: turbine, sealevel, ibc, poh"
echo "Each has: weights.rs, WeightInfo trait, Config type, runtime config"
