//! Autogenerated weights for pallet_turbine
use core::marker::PhantomData;
use frame_support::{traits::Get, weights::Weight};

/// Weight functions for pallet_turbine.
pub trait WeightInfo {
    fn register_shard() -> Weight;
    fn rebuild_tree(v: u32) -> Weight;
    fn mark_block_propagated() -> Weight;
}

/// Default weights using reasonable estimates.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
    fn register_shard() -> Weight {
        // Storage: read shard count, write shard entry
        Weight::from_parts(50_000, 0)
            .saturating_add(T::DbWeight::get().reads(1))
            .saturating_add(T::DbWeight::get().writes(1))
    }
    fn rebuild_tree(v: u32) -> Weight {
        // O(n) tree rebuild over validators
        Weight::from_parts(20_000, 0)
            .saturating_add(Weight::from_parts(2_000, 0).saturating_mul(v.into()))
            .saturating_add(T::DbWeight::get().reads(1))
            .saturating_add(T::DbWeight::get().writes(1))
    }
    fn mark_block_propagated() -> Weight {
        // Simple storage write
        Weight::from_parts(20_000, 0)
            .saturating_add(T::DbWeight::get().reads(1))
            .saturating_add(T::DbWeight::get().writes(1))
    }
}

impl WeightInfo for () {
    fn register_shard() -> Weight { Weight::from_parts(10_000, 0) }
    fn rebuild_tree(_v: u32) -> Weight { Weight::from_parts(10_000, 0) }
    fn mark_block_propagated() -> Weight { Weight::from_parts(10_000, 0) }
}
