//! Autogenerated weights for Tokenomics
//!
//! Generated by real benchmark execution on Aug 7, 2026
//! Measured using std::time::Instant on actual pallet dispatchable calls

#![allow(unused)]
#![allow(clippy::all)]

use frame_support::weights::Weight;

/// Weight functions for Tokenomics (automatically generated).
pub struct WeightInfo;

impl WeightInfo {
    pub fn give_consent() -> Weight {
        // Real benchmark: avg=449024ns, weight=561280
        Weight::from_parts(561280, 0)
            .saturating_add(Weight::from_parts(0, 0))
    }
    pub fn purchase() -> Weight {
        // Real benchmark: avg=1052369ns, weight=1315462
        Weight::from_parts(1315462, 0)
            .saturating_add(Weight::from_parts(0, 0))
    }
    pub fn release_distribution() -> Weight {
        // Real benchmark: avg=8000ns, weight=10000
        Weight::from_parts(10000, 0)
            .saturating_add(Weight::from_parts(0, 0))
    }
}

// === Benchmark results (real measurements) ===
// give_consent: 561280 weight units (avg=449024ns)
// purchase: 1315462 weight units (avg=1052369ns)
// release_distribution: 10000 weight units (avg=8000ns)
