
//! Autogenerated weights for `pallet_fungible_tokens`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 58.0.0
//! DATE: 2026-08-13, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `ubuntu-32gb-nbg1-2`, CPU: `AMD EPYC-Milan Processor`
//! WASM-EXECUTION: `Compiled`, CHAIN: `Some("dev")`, DB CACHE: 1024

// Executed Command:
// ./target/release/verdis
// benchmark
// pallet
// --chain=dev
// --pallet=pallet_fungible_tokens
// --extrinsic=*
// --output=pallets/fungible-tokens/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::Weight};
use core::marker::PhantomData;

/// Weight functions for `pallet_fungible_tokens`.
pub struct WeightInfo<T>(PhantomData<T>);
impl<T: frame_system::Config> crate::WeightInfo for WeightInfo<T> {
	/// Storage: `FungibleTokens::TokensByOwner` (r:1 w:1)
	/// Proof: `FungibleTokens::TokensByOwner` (`max_values`: None, `max_size`: Some(850), added: 3325, mode: `MaxEncodedLen`)
	/// Storage: `FungibleTokens::NextTokenId` (r:1 w:1)
	/// Proof: `FungibleTokens::NextTokenId` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `FungibleTokens::Tokens` (r:0 w:1)
	/// Proof: `FungibleTokens::Tokens` (`max_values`: None, `max_size`: Some(140), added: 2615, mode: `MaxEncodedLen`)
	fn create() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `4`
		//  Estimated: `4315`
		// Minimum execution time: 28_433_000 picoseconds.
		Weight::from_parts(32_088_000, 0)
			.saturating_add(Weight::from_parts(0, 4315))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	/// Storage: `FungibleTokens::Tokens` (r:1 w:1)
	/// Proof: `FungibleTokens::Tokens` (`max_values`: None, `max_size`: Some(140), added: 2615, mode: `MaxEncodedLen`)
	/// Storage: `FungibleTokens::TokenBalances` (r:1 w:1)
	/// Proof: `FungibleTokens::TokenBalances` (`max_values`: None, `max_size`: Some(88), added: 2563, mode: `MaxEncodedLen`)
	fn mint() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `233`
		//  Estimated: `3605`
		// Minimum execution time: 17_046_000 picoseconds.
		Weight::from_parts(19_419_000, 0)
			.saturating_add(Weight::from_parts(0, 3605))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	/// Storage: `FungibleTokens::Tokens` (r:1 w:1)
	/// Proof: `FungibleTokens::Tokens` (`max_values`: None, `max_size`: Some(140), added: 2615, mode: `MaxEncodedLen`)
	/// Storage: `FungibleTokens::TokenBalances` (r:1 w:1)
	/// Proof: `FungibleTokens::TokenBalances` (`max_values`: None, `max_size`: Some(88), added: 2563, mode: `MaxEncodedLen`)
	fn burn() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `343`
		//  Estimated: `3605`
		// Minimum execution time: 18_698_000 picoseconds.
		Weight::from_parts(21_002_000, 0)
			.saturating_add(Weight::from_parts(0, 3605))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	/// Storage: `FungibleTokens::Tokens` (r:1 w:0)
	/// Proof: `FungibleTokens::Tokens` (`max_values`: None, `max_size`: Some(140), added: 2615, mode: `MaxEncodedLen`)
	/// Storage: `FungibleTokens::TokenBalances` (r:2 w:2)
	/// Proof: `FungibleTokens::TokenBalances` (`max_values`: None, `max_size`: Some(88), added: 2563, mode: `MaxEncodedLen`)
	fn transfer() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `343`
		//  Estimated: `6116`
		// Minimum execution time: 22_004_000 picoseconds.
		Weight::from_parts(24_667_000, 0)
			.saturating_add(Weight::from_parts(0, 6116))
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	/// Storage: `FungibleTokens::Tokens` (r:1 w:0)
	/// Proof: `FungibleTokens::Tokens` (`max_values`: None, `max_size`: Some(140), added: 2615, mode: `MaxEncodedLen`)
	/// Storage: `FungibleTokens::Allowances` (r:0 w:1)
	/// Proof: `FungibleTokens::Allowances` (`max_values`: None, `max_size`: Some(120), added: 2595, mode: `MaxEncodedLen`)
	fn approve() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `233`
		//  Estimated: `3605`
		// Minimum execution time: 12_870_000 picoseconds.
		Weight::from_parts(15_193_000, 0)
			.saturating_add(Weight::from_parts(0, 3605))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `FungibleTokens::Tokens` (r:1 w:0)
	/// Proof: `FungibleTokens::Tokens` (`max_values`: None, `max_size`: Some(140), added: 2615, mode: `MaxEncodedLen`)
	/// Storage: `FungibleTokens::Allowances` (r:1 w:1)
	/// Proof: `FungibleTokens::Allowances` (`max_values`: None, `max_size`: Some(120), added: 2595, mode: `MaxEncodedLen`)
	/// Storage: `FungibleTokens::TokenBalances` (r:2 w:2)
	/// Proof: `FungibleTokens::TokenBalances` (`max_values`: None, `max_size`: Some(88), added: 2563, mode: `MaxEncodedLen`)
	fn transfer_from() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `489`
		//  Estimated: `6116`
		// Minimum execution time: 28_864_000 picoseconds.
		Weight::from_parts(32_248_000, 0)
			.saturating_add(Weight::from_parts(0, 6116))
			.saturating_add(T::DbWeight::get().reads(4))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	/// Storage: `FungibleTokens::Tokens` (r:1 w:0)
	/// Proof: `FungibleTokens::Tokens` (`max_values`: None, `max_size`: Some(140), added: 2615, mode: `MaxEncodedLen`)
	/// Storage: `FungibleTokens::TokenMetadataMap` (r:0 w:1)
	/// Proof: `FungibleTokens::TokenMetadataMap` (`max_values`: None, `max_size`: Some(284), added: 2759, mode: `MaxEncodedLen`)
	/// The range of component `n` is `[1, 128]`.
	fn set_metadata(n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `233`
		//  Estimated: `3605`
		// Minimum execution time: 12_880_000 picoseconds.
		Weight::from_parts(14_856_318, 0)
			.saturating_add(Weight::from_parts(0, 3605))
			// Standard Error: 116
			.saturating_add(Weight::from_parts(2_406, 0).saturating_mul(n.into()))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `FungibleTokens::Tokens` (r:1 w:1)
	/// Proof: `FungibleTokens::Tokens` (`max_values`: None, `max_size`: Some(140), added: 2615, mode: `MaxEncodedLen`)
	fn freeze() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `233`
		//  Estimated: `3605`
		// Minimum execution time: 12_258_000 picoseconds.
		Weight::from_parts(13_881_000, 0)
			.saturating_add(Weight::from_parts(0, 3605))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `FungibleTokens::Tokens` (r:1 w:1)
	/// Proof: `FungibleTokens::Tokens` (`max_values`: None, `max_size`: Some(140), added: 2615, mode: `MaxEncodedLen`)
	fn thaw() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `233`
		//  Estimated: `3605`
		// Minimum execution time: 12_178_000 picoseconds.
		Weight::from_parts(13_820_000, 0)
			.saturating_add(Weight::from_parts(0, 3605))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `FungibleTokens::Tokens` (r:1 w:1)
	/// Proof: `FungibleTokens::Tokens` (`max_values`: None, `max_size`: Some(140), added: 2615, mode: `MaxEncodedLen`)
	/// Storage: `FungibleTokens::TokensByOwner` (r:1 w:1)
	/// Proof: `FungibleTokens::TokensByOwner` (`max_values`: None, `max_size`: Some(850), added: 3325, mode: `MaxEncodedLen`)
	/// Storage: `FungibleTokens::TokenMetadataMap` (r:0 w:1)
	/// Proof: `FungibleTokens::TokenMetadataMap` (`max_values`: None, `max_size`: Some(284), added: 2759, mode: `MaxEncodedLen`)
	fn destroy() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `279`
		//  Estimated: `4315`
		// Minimum execution time: 31_457_000 picoseconds.
		Weight::from_parts(33_400_000, 0)
			.saturating_add(Weight::from_parts(0, 4315))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	/// Storage: `FungibleTokens::Tokens` (r:1 w:0)
	/// Proof: `FungibleTokens::Tokens` (`max_values`: None, `max_size`: Some(140), added: 2615, mode: `MaxEncodedLen`)
	/// Storage: `FungibleTokens::TokenBalances` (r:101 w:101)
	/// Proof: `FungibleTokens::TokenBalances` (`max_values`: None, `max_size`: Some(88), added: 2563, mode: `MaxEncodedLen`)
	/// The range of component `b` is `[1, 100]`.
	fn batch_transfer(b: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `343`
		//  Estimated: `3605 + b * (2563 ±0)`
		// Minimum execution time: 22_294_000 picoseconds.
		Weight::from_parts(12_884_355, 0)
			.saturating_add(Weight::from_parts(0, 3605))
			// Standard Error: 2_812
			.saturating_add(Weight::from_parts(7_133_087, 0).saturating_mul(b.into()))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().reads((1_u64).saturating_mul(b.into())))
			.saturating_add(T::DbWeight::get().writes(1))
			.saturating_add(T::DbWeight::get().writes((1_u64).saturating_mul(b.into())))
			.saturating_add(Weight::from_parts(0, 2563).saturating_mul(b.into()))
	}
	/// Storage: `FungibleTokens::Tokens` (r:1 w:1)
	/// Proof: `FungibleTokens::Tokens` (`max_values`: None, `max_size`: Some(140), added: 2615, mode: `MaxEncodedLen`)
	/// Storage: `FungibleTokens::TokensByOwner` (r:2 w:2)
	/// Proof: `FungibleTokens::TokensByOwner` (`max_values`: None, `max_size`: Some(850), added: 3325, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn transfer_ownership() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `419`
		//  Estimated: `7640`
		// Minimum execution time: 51_688_000 picoseconds.
		Weight::from_parts(54_271_000, 0)
			.saturating_add(Weight::from_parts(0, 7640))
			.saturating_add(T::DbWeight::get().reads(4))
			.saturating_add(T::DbWeight::get().writes(4))
	}
}
