
//! Autogenerated weights for `pallet_fungible_tokens`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 58.0.0
//! DATE: 2026-08-09, STEPS: `20`, REPEAT: `10`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `ubuntu-32gb-nbg1-2`, CPU: `AMD EPYC-Milan Processor`
//! WASM-EXECUTION: `Compiled`, CHAIN: `Some("dev")`, DB CACHE: 1024

// Executed Command:
// ./target/release/verdis
// benchmark
// pallet
// --chain
// dev
// --pallet
// pallet_fungible_tokens
// --extrinsic
// *
// --steps
// 20
// --repeat
// 10
// --output
// /tmp/weights_fungible_tokens.rs
// --template
// node/src/weight-template.hbs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::Weight};
use core::marker::PhantomData;

/// Weight functions for `pallet_fungible_tokens`.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> crate::WeightInfo for SubstrateWeight<T> {
	/// Storage: `FungibleTokens::TokensByOwner` (r:1 w:1)
	/// Proof: `FungibleTokens::TokensByOwner` (`max_values`: None, `max_size`: Some(850), added: 3325, mode: `MaxEncodedLen`)
	/// Storage: `FungibleTokens::NextTokenId` (r:1 w:1)
	/// Proof: `FungibleTokens::NextTokenId` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `FungibleTokens::Tokens` (r:0 w:1)
	/// Proof: `FungibleTokens::Tokens` (`max_values`: None, `max_size`: Some(124), added: 2599, mode: `MaxEncodedLen`)
	fn create() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `4`
		//  Estimated: `4315`
		// Minimum execution time: 28_122_000 picoseconds.
		Weight::from_parts(30_267_000, 0)
			.saturating_add(Weight::from_parts(0, 4315))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	/// Storage: `FungibleTokens::Tokens` (r:1 w:1)
	/// Proof: `FungibleTokens::Tokens` (`max_values`: None, `max_size`: Some(124), added: 2599, mode: `MaxEncodedLen`)
	/// Storage: `FungibleTokens::TokenBalances` (r:1 w:1)
	/// Proof: `FungibleTokens::TokenBalances` (`max_values`: None, `max_size`: Some(88), added: 2563, mode: `MaxEncodedLen`)
	fn mint() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `217`
		//  Estimated: `3589`
		// Minimum execution time: 16_885_000 picoseconds.
		Weight::from_parts(18_678_000, 0)
			.saturating_add(Weight::from_parts(0, 3589))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	/// Storage: `FungibleTokens::Tokens` (r:1 w:1)
	/// Proof: `FungibleTokens::Tokens` (`max_values`: None, `max_size`: Some(124), added: 2599, mode: `MaxEncodedLen`)
	/// Storage: `FungibleTokens::TokenBalances` (r:1 w:1)
	/// Proof: `FungibleTokens::TokenBalances` (`max_values`: None, `max_size`: Some(88), added: 2563, mode: `MaxEncodedLen`)
	fn burn() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `327`
		//  Estimated: `3589`
		// Minimum execution time: 18_668_000 picoseconds.
		Weight::from_parts(20_441_000, 0)
			.saturating_add(Weight::from_parts(0, 3589))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	/// Storage: `FungibleTokens::Tokens` (r:1 w:0)
	/// Proof: `FungibleTokens::Tokens` (`max_values`: None, `max_size`: Some(124), added: 2599, mode: `MaxEncodedLen`)
	/// Storage: `FungibleTokens::TokenBalances` (r:2 w:2)
	/// Proof: `FungibleTokens::TokenBalances` (`max_values`: None, `max_size`: Some(88), added: 2563, mode: `MaxEncodedLen`)
	fn transfer() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `327`
		//  Estimated: `6116`
		// Minimum execution time: 21_592_000 picoseconds.
		Weight::from_parts(23_274_000, 0)
			.saturating_add(Weight::from_parts(0, 6116))
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	/// Storage: `FungibleTokens::Tokens` (r:1 w:0)
	/// Proof: `FungibleTokens::Tokens` (`max_values`: None, `max_size`: Some(124), added: 2599, mode: `MaxEncodedLen`)
	/// Storage: `FungibleTokens::Allowances` (r:0 w:1)
	/// Proof: `FungibleTokens::Allowances` (`max_values`: None, `max_size`: Some(120), added: 2595, mode: `MaxEncodedLen`)
	fn approve() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `217`
		//  Estimated: `3589`
		// Minimum execution time: 12_699_000 picoseconds.
		Weight::from_parts(14_021_000, 0)
			.saturating_add(Weight::from_parts(0, 3589))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `FungibleTokens::Tokens` (r:1 w:0)
	/// Proof: `FungibleTokens::Tokens` (`max_values`: None, `max_size`: Some(124), added: 2599, mode: `MaxEncodedLen`)
	/// Storage: `FungibleTokens::Allowances` (r:1 w:1)
	/// Proof: `FungibleTokens::Allowances` (`max_values`: None, `max_size`: Some(120), added: 2595, mode: `MaxEncodedLen`)
	/// Storage: `FungibleTokens::TokenBalances` (r:2 w:2)
	/// Proof: `FungibleTokens::TokenBalances` (`max_values`: None, `max_size`: Some(88), added: 2563, mode: `MaxEncodedLen`)
	fn transfer_from() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `473`
		//  Estimated: `6116`
		// Minimum execution time: 28_803_000 picoseconds.
		Weight::from_parts(30_507_000, 0)
			.saturating_add(Weight::from_parts(0, 6116))
			.saturating_add(T::DbWeight::get().reads(4))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	/// Storage: `FungibleTokens::Tokens` (r:1 w:0)
	/// Proof: `FungibleTokens::Tokens` (`max_values`: None, `max_size`: Some(124), added: 2599, mode: `MaxEncodedLen`)
	/// Storage: `FungibleTokens::TokenMetadataMap` (r:0 w:1)
	/// Proof: `FungibleTokens::TokenMetadataMap` (`max_values`: None, `max_size`: Some(284), added: 2759, mode: `MaxEncodedLen`)
	/// The range of component `n` is `[1, 128]`.
	fn set_metadata(n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `217`
		//  Estimated: `3589`
		// Minimum execution time: 13_220_000 picoseconds.
		Weight::from_parts(15_010_856, 0)
			.saturating_add(Weight::from_parts(0, 3589))
			// Standard Error: 105
			.saturating_add(Weight::from_parts(3_470, 0).saturating_mul(n.into()))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `FungibleTokens::Tokens` (r:1 w:1)
	/// Proof: `FungibleTokens::Tokens` (`max_values`: None, `max_size`: Some(124), added: 2599, mode: `MaxEncodedLen`)
	fn freeze() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `217`
		//  Estimated: `3589`
		// Minimum execution time: 12_158_000 picoseconds.
		Weight::from_parts(13_380_000, 0)
			.saturating_add(Weight::from_parts(0, 3589))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `FungibleTokens::Tokens` (r:1 w:1)
	/// Proof: `FungibleTokens::Tokens` (`max_values`: None, `max_size`: Some(124), added: 2599, mode: `MaxEncodedLen`)
	fn thaw() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `217`
		//  Estimated: `3589`
		// Minimum execution time: 12_008_000 picoseconds.
		Weight::from_parts(13_280_000, 0)
			.saturating_add(Weight::from_parts(0, 3589))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `FungibleTokens::Tokens` (r:1 w:1)
	/// Proof: `FungibleTokens::Tokens` (`max_values`: None, `max_size`: Some(124), added: 2599, mode: `MaxEncodedLen`)
	/// Storage: `FungibleTokens::TokensByOwner` (r:1 w:1)
	/// Proof: `FungibleTokens::TokensByOwner` (`max_values`: None, `max_size`: Some(850), added: 3325, mode: `MaxEncodedLen`)
	/// Storage: `FungibleTokens::TokenMetadataMap` (r:0 w:1)
	/// Proof: `FungibleTokens::TokenMetadataMap` (`max_values`: None, `max_size`: Some(284), added: 2759, mode: `MaxEncodedLen`)
	fn destroy() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `263`
		//  Estimated: `4315`
		// Minimum execution time: 31_658_000 picoseconds.
		Weight::from_parts(33_791_000, 0)
			.saturating_add(Weight::from_parts(0, 4315))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	/// Storage: `FungibleTokens::Tokens` (r:1 w:0)
	/// Proof: `FungibleTokens::Tokens` (`max_values`: None, `max_size`: Some(124), added: 2599, mode: `MaxEncodedLen`)
	/// Storage: `FungibleTokens::TokenBalances` (r:101 w:101)
	/// Proof: `FungibleTokens::TokenBalances` (`max_values`: None, `max_size`: Some(88), added: 2563, mode: `MaxEncodedLen`)
	/// The range of component `b` is `[1, 100]`.
	fn batch_transfer(b: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `327`
		//  Estimated: `3589 + b * (2563 ±0)`
		// Minimum execution time: 22_994_000 picoseconds.
		Weight::from_parts(19_764_696, 0)
			.saturating_add(Weight::from_parts(0, 3589))
			// Standard Error: 3_335
			.saturating_add(Weight::from_parts(7_387_790, 0).saturating_mul(b.into()))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().reads((1_u64).saturating_mul(b.into())))
			.saturating_add(T::DbWeight::get().writes(1))
			.saturating_add(T::DbWeight::get().writes((1_u64).saturating_mul(b.into())))
			.saturating_add(Weight::from_parts(0, 2563).saturating_mul(b.into()))
	}
	/// Storage: `FungibleTokens::Tokens` (r:1 w:1)
	/// Proof: `FungibleTokens::Tokens` (`max_values`: None, `max_size`: Some(124), added: 2599, mode: `MaxEncodedLen`)
	/// Storage: `FungibleTokens::TokensByOwner` (r:2 w:2)
	/// Proof: `FungibleTokens::TokensByOwner` (`max_values`: None, `max_size`: Some(850), added: 3325, mode: `MaxEncodedLen`)
	fn transfer_ownership() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `263`
		//  Estimated: `7640`
		// Minimum execution time: 21_512_000 picoseconds.
		Weight::from_parts(23_516_000, 0)
			.saturating_add(Weight::from_parts(0, 7640))
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(3))
	}
}
